services:
  - type: web
    name: aquaintelli
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker --chdir backend app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: SQL_DATABASE_URL
        value: sqlite+aiosqlite:///./aquaintelli.db
      - key: MONGO_MOCK
        value: "true"
      - key: NEO4J_MOCK
        value: "true"
      - key: CORS_ORIGINS
        value: "*"
